# docker-compose.yml

services:
  backend:
    build:
      context: .
      dockerfile: book_service/Dockerfile
    container_name: books-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - db
      - redis

  cli:
    build:
      context: .
      dockerfile: interface/Dockerfile
    container_name: books-cli
    env_file:
      - .env
    depends_on:
      - backend
      - redis
    stdin_open: true
    tty: true
    volumes:
      - ./interface:/app/interface
      - ./scripts:/app/scripts

  db:
    image: postgres:15-alpine
    container_name: books-db
    environment:
      POSTGRES_USER: book
      POSTGRES_PASSWORD: book
      POSTGRES_DB: books
      LANG: en_US.utf8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: books-redis
    ports:
      - "6379:6379"
  worker:
    build:
      context: .
      dockerfile: book_service/Dockerfile
    container_name: books-worker
    env_file:
      - .env
    depends_on:
      - redis
      - backend
    environment:
      - PYTHONPATH=/app/book_service
    command: python -m book_service.worker.main

volumes:
  postgres_data:
