services:
  db:
    image: postgres:15-alpine
    container_name: books-db
    environment:
      - POSTGRES_USER=book
      - POSTGRES_PASSWORD=book
      - POSTGRES_DB=books
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: